server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址 本地nacas访问地址
        server-addr: 192.168.187.150:1111 # 换成nginx的1111端口，做负债均衡

management:
  endpoints:
    web:
      exposure:
        include: '*'